// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SensorClient is the client API for Sensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorClient interface {
	// Sends a greeting
	GetReading(ctx context.Context, in *GetReadingRequest, opts ...grpc.CallOption) (*Reading, error)
}

type sensorClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorClient(cc grpc.ClientConnInterface) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) GetReading(ctx context.Context, in *GetReadingRequest, opts ...grpc.CallOption) (*Reading, error) {
	out := new(Reading)
	err := c.cc.Invoke(ctx, "/proto.Sensor/GetReading", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorServer is the server API for Sensor service.
// All implementations must embed UnimplementedSensorServer
// for forward compatibility
type SensorServer interface {
	// Sends a greeting
	GetReading(context.Context, *GetReadingRequest) (*Reading, error)
	mustEmbedUnimplementedSensorServer()
}

// UnimplementedSensorServer must be embedded to have forward compatible implementations.
type UnimplementedSensorServer struct {
}

func (UnimplementedSensorServer) GetReading(context.Context, *GetReadingRequest) (*Reading, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReading not implemented")
}
func (UnimplementedSensorServer) mustEmbedUnimplementedSensorServer() {}

// UnsafeSensorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServer will
// result in compilation errors.
type UnsafeSensorServer interface {
	mustEmbedUnimplementedSensorServer()
}

func RegisterSensorServer(s grpc.ServiceRegistrar, srv SensorServer) {
	s.RegisterService(&Sensor_ServiceDesc, srv)
}

func _Sensor_GetReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorServer).GetReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Sensor/GetReading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorServer).GetReading(ctx, req.(*GetReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Sensor_ServiceDesc is the grpc.ServiceDesc for Sensor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sensor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReading",
			Handler:    _Sensor_GetReading_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/reading.proto",
}
